name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: read

jobs:
  specs:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.5.0-preview1'
          - '3.4'
          - '3.3'
          - '3.2'
        include:
          - ruby: '3.4'
            coverage: 'true'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Install package dependencies
        run: "[ -e $APT_DEPS ] || sudo apt-get install -y --no-install-recommends $APT_DEPS"

      - name: Set up Ruby
        uses: ruby/setup-ruby@ab177d40ee5483edb974554986f56b33477e21d0 # v1.265.0
        with:
          ruby-version: ${{matrix.ruby}}
          bundler: 'latest'
          self-hosted: false

      - name: Install latest bundler
        run: |
          gem install bundler --no-document
          gem update --system --no-document
          bundle config set without 'tools benchmarks docs'

      - name: Bundle install
        run: |
          bundle config set without development
          bundle install --jobs 4 --retry 3

      - name: Run all tests
        env:
          GITHUB_COVERAGE: ${{matrix.coverage}}
        run: bundle exec rspec

  coditsu:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: Download Coditsu script
        run: |
          curl -sSL https://api.coditsu.io/run/ci -o coditsu_script.sh
          chmod +x coditsu_script.sh
      - name: Verify Coditsu script checksum
        run: |
          EXPECTED_SHA256="0aecc5aa010f53fca264548a41467a2b0a1208d750ce1da3e98a217304cacbbc"
          ACTUAL_SHA256=$(sha256sum coditsu_script.sh | awk '{ print $1 }')
          if [ "$ACTUAL_SHA256" != "$EXPECTED_SHA256" ]; then
            echo "::error::Checksum verification failed. Expected $EXPECTED_SHA256 but got $ACTUAL_SHA256."
            exit 1
          fi
      - name: Run Coditsu
        run: ./coditsu_script.sh

  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    if: always()
    needs:
      - coditsu
      - specs
    steps:
      - name: Check all jobs passed
        if: |
          contains(needs.*.result, 'failure') ||
          contains(needs.*.result, 'cancelled') ||
          contains(needs.*.result, 'skipped')
        run: exit 1
      - run: echo "All CI checks passed!"
