name: Trigger Wiki Refresh

on:
  release:
    types: [published]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  trigger-wiki-refresh:
    runs-on: ubuntu-latest
    environment: wiki-trigger
    steps:
      - name: Trigger wiki refresh on release
        if: github.event_name == 'release'
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.WIKI_REPO_TOKEN }}
          repository: karafka/wiki
          event-type: gem-release
          client-payload: |
            {
              "repository": "${{ github.repository }}",
              "release_tag": "${{ github.event.release.tag_name }}",
              "release_name": "${{ github.event.release.name }}"
            }

      - name: Trigger wiki refresh on master push
        if: github.event_name == 'push'
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.WIKI_REPO_TOKEN }}
          repository: karafka/wiki
          event-type: master-push
          client-payload: |
            {
              "repository": "${{ github.repository }}",
              "commit_sha": "${{ github.sha }}",
              "commit_message": "${{ github.event.head_commit.message }}"
            }
